name: AutomatedActions

on:
  push:
    branches:
      - 'develop'
      - 'main'
      - 'staging'
  pull_request:
    branches:
      - 'main'
      - 'develop'
      - 'staging'

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 18.15
      - name: Install Dependencies
        run: yarn install
      - name: 'lint'
        run: yarn run lint
      - name: 'build'
        run: yarn run build
      - name: 'test'
        run: yarn run jest-test
